#!/bin/bash

name="$1"
if [[ -z "$name" ]]; then
    echo "Error: A name is required."
    echo "Try 'vm-attach --help' for usage."
    exit 1
elif [[ $name == "-h" || $name == "--help" ]]; then
    echo "Usage: vm-attach NAME"
    echo "Attach to a running Podman container."
    echo ""
    echo "Options:"
    echo "--help, -h          Show this help message and exit."
    echo ""
    exit 0
fi
podman attach "$name"
