#!/bin/bash

name="$1"
if [[ -z "$name" ]]; then
    echo "Error: A name is required."
    echo "Try 'vm-info --help' for usage."
    exit 1
elif [[ $name == "-h" || $name == "--help" ]]; then
    echo "Usage: vm-info NAME"
    echo "Display information about an existing Podman container."
    echo ""
    echo "Options:"
    echo "--help, -h          Show this help message and exit."
    echo ""
    exit 0
fi
echo "Name : $(podman container inspect --format "{{.Name}}" "$name")"
echo "Status : $(podman container inspect --format "{{.State.Status}}" "$name")"
echo "Image : $(podman container inspect --format "{{.ImageName}}" "$name")"
echo "Created : $(podman container inspect --format "{{.Created}}" "$name")"
echo "Finished At : $(podman container inspect --format "{{.State.FinishedAt}}" "$name")"
echo "Network Settings : $(podman container inspect --format "{{.NetworkSettings.Networks}}" "$name")"
echo "Exposed Ports : $(podman container inspect --format "{{.NetworkSettings.Ports}}" "$name")"
