#!/bin/bash

name="$1"
if [[ -z "$name" ]]; then
    echo "Error: A name is required."
    echo "Try 'vn-rm --help' for usage."
    exit 1
elif [[ $name == "-h" || $name == "--help" ]]; then
    echo "Usage: vn-rm NAME"
    echo "Remove an existing Podman network."
    echo ""
    echo "Options:"
    echo "--help, -h          Show this help message and exit."
    echo ""
    exit 0
fi
podman network rm "$name"
