# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './UI2/creationPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys, subprocess

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.cancelButton = QtWidgets.QPushButton(self.centralwidget)
        self.cancelButton.setGeometry(QtCore.QRect(450, 440, 88, 34))
        self.cancelButton.setObjectName("cancelButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 321, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.nameLabel = QtWidgets.QLabel(self.centralwidget)
        self.nameLabel.setGeometry(QtCore.QRect(10, 70, 58, 18))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.nameLabel.setFont(font)
        self.nameLabel.setObjectName("nameLabel")
        self.nameLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.nameLineEdit.setGeometry(QtCore.QRect(70, 60, 211, 41))
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.guiLabel = QtWidgets.QLabel(self.centralwidget)
        self.guiLabel.setGeometry(QtCore.QRect(10, 170, 431, 18))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.guiLabel.setFont(font)
        self.guiLabel.setObjectName("guiLabel")
        self.guiCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.guiCheckBox.setGeometry(QtCore.QRect(10, 200, 84, 22))
        self.guiCheckBox.setObjectName("guiCheckBox")
        self.network1Label = QtWidgets.QLabel(self.centralwidget)
        self.network1Label.setGeometry(QtCore.QRect(10, 240, 441, 18))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.network1Label.setFont(font)
        self.network1Label.setObjectName("network1Label")
        self.isolatedLabel = QtWidgets.QLabel(self.centralwidget)
        self.isolatedLabel.setGeometry(QtCore.QRect(10, 330, 431, 18))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.isolatedLabel.setFont(font)
        self.isolatedLabel.setObjectName("isolatedLabel")
        self.isolatedCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.isolatedCheckBox.setGeometry(QtCore.QRect(10, 360, 84, 22))
        self.isolatedCheckBox.setObjectName("isolatedCheckBox")
        self.networkLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.networkLineEdit.setGeometry(QtCore.QRect(10, 270, 271, 41))
        self.networkLineEdit.setText("")
        self.networkLineEdit.setFrame(True)
        self.networkLineEdit.setDragEnabled(False)
        self.networkLineEdit.setClearButtonEnabled(False)
        self.networkLineEdit.setObjectName("networkLineEdit")
        self.network2Label = QtWidgets.QLabel(self.centralwidget)
        self.network2Label.setGeometry(QtCore.QRect(290, 280, 201, 18))
        self.network2Label.setObjectName("network2Label")
        self.createButton = QtWidgets.QPushButton(self.centralwidget)
        self.createButton.setGeometry(QtCore.QRect(540, 440, 88, 34))
        self.createButton.setObjectName("createButton")
        self.imageComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.imageComboBox.setGeometry(QtCore.QRect(160, 110, 241, 41))
        self.imageComboBox.setObjectName("imageComboBox")
        self.imageLabel = QtWidgets.QLabel(self.centralwidget)
        self.imageLabel.setGeometry(QtCore.QRect(10, 120, 151, 18))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.imageLabel.setFont(font)
        self.imageLabel.setObjectName("imageLabel")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "theVirtualThings - VM Creation page"))
        self.cancelButton.setText(_translate("MainWindow", "Cancel"))
        self.label.setText(_translate("MainWindow", "Virtual Machine - Creation"))
        self.nameLabel.setText(_translate("MainWindow", "Name : "))
        self.guiLabel.setText(_translate("MainWindow", "Does the VM needs to run a graphical interface ? (XFCE 4)"))
        self.guiCheckBox.setText(_translate("MainWindow", "Yes "))
        self.network1Label.setText(_translate("MainWindow", "Does the VM needs to be connected to a Virtual Network ?"))
        self.isolatedLabel.setText(_translate("MainWindow", "Does the VM needs to be isolated in a private network ?"))
        self.isolatedCheckBox.setText(_translate("MainWindow", "Yes "))
        self.network2Label.setText(_translate("MainWindow", "Leave Empty if you don\'t want to"))
        self.createButton.setText(_translate("MainWindow", "Create"))
        self.imageLabel.setText(_translate("MainWindow", "Select your image :"))

        self.imageComboBox.addItems(self.getImageList())
        self.cancelButton.clicked.connect(sys.exit)
        self.createButton.clicked.connect(self.createVM)

    def getImageList(self):
        images = ["debian","archlinux", "fedora"]
        return images
        
    def createVM(self):
        name = self.nameLineEdit.text()
        image = self.imageComboBox.currentText()
        gui = self.guiCheckBox.isChecked()
        vnet = self.networkLineEdit.text()
        isolated = self.isolatedCheckBox.isChecked()

        args = ""
        if gui:
            args += " -x"
        if vnet != "":
            args += " -c {}".format(vnet)
        if isolated:
            args += " -i"
        
        command = "vm-create {} -d {} {}".format(args,image,name)
        p = subprocess.Popen(command, stdout=subprocess.PIPE, shell=True)
        (output, err) = p.communicate()
        p_status = p.wait()
        if p_status != 0:
            dialog = QtWidgets.QMessageBox()
            dialog.setWindowTitle("theVirtualThings - Error")
            dialog.setIcon(QtWidgets.QMessageBox.Critical)
            dialog.setText("An error occured while creating the VM.\nPlease check the name is not already used and that the image exists.")
            dialog.exec_()
            return False
        else:
            dialog = QtWidgets.QMessageBox()
            dialog.setWindowTitle("theVirtualThings - Success")
            dialog.setIcon(QtWidgets.QMessageBox.Information)
            dialog.setText("The VM has been created successfully :)")
            dialog.exec_()
            app.quit()




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
