# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'creationPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os, subprocess


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.createButton = QtWidgets.QPushButton(self.centralwidget)
        self.createButton.setGeometry(QtCore.QRect(390, 440, 141, 34))
        self.createButton.setObjectName("createButton")
        self.cancelButton = QtWidgets.QPushButton(self.centralwidget)
        self.cancelButton.setGeometry(QtCore.QRect(290, 440, 88, 34))
        self.cancelButton.setObjectName("cancelButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 321, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 58, 18))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(70, 60, 211, 41))
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 170, 431, 18))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(10, 200, 84, 22))
        self.checkBox.setObjectName("checkBox")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 240, 441, 18))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 330, 431, 18))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.checkBox_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_3.setGeometry(QtCore.QRect(10, 360, 84, 22))
        self.checkBox_3.setObjectName("checkBox_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 270, 271, 41))
        self.lineEdit_2.setText("")
        self.lineEdit_2.setFrame(True)
        self.lineEdit_2.setDragEnabled(False)
        self.lineEdit_2.setClearButtonEnabled(False)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(290, 280, 201, 18))
        self.label_6.setObjectName("label_6")
        self.createButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.createButton_2.setGeometry(QtCore.QRect(540, 440, 88, 34))
        self.createButton_2.setObjectName("createButton_2")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(160, 110, 241, 41))
        self.comboBox.setObjectName("comboBox")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 120, 151, 18))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.comboBox.addItems(self.getImageList())

        self.cancelButton.clicked.connect(MainWindow.close)
        self.createButton.clicked.connect(self.createVM)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "theVirtualThings - VM Creation page"))
        self.createButton.setText(_translate("MainWindow", "Create and run now"))
        self.cancelButton.setText(_translate("MainWindow", "Cancel"))
        self.label.setText(_translate("MainWindow", "Virtual Machine creation page"))
        self.label_2.setText(_translate("MainWindow", "Name : "))
        self.label_3.setText(_translate("MainWindow", "Does the VM needs to run a graphical interface ? (XFCE 4)"))
        self.checkBox.setText(_translate("MainWindow", "Yes "))
        self.label_4.setText(_translate("MainWindow", "Does the VM needs to be connected to a Virtual Network ?"))
        self.label_5.setText(_translate("MainWindow", "Does the VM needs to be isolated in a private network ?"))
        self.checkBox_3.setText(_translate("MainWindow", "Yes "))
        self.label_6.setText(_translate("MainWindow", "Leave Empty if you don\'t want to"))
        self.createButton_2.setText(_translate("MainWindow", "Create"))
        self.label_7.setText(_translate("MainWindow", "Select your image :"))

    def getImageList(self):
        images = ["debian","archlinux", "fedora"]
        return images

        p = subprocess.Popen("vm-ls-images -n", stdout=subprocess.PIPE, shell=True)
        (output, err) = p.communicate()
        p_status = p.wait()
        output = output.split(b'\n')
        for line in output:
            if line != b'':
                images.append(line.decode('utf-8'))
        #for line in result.stdout.readlines():
        #    print(line)
        
    
    def createVM(self):
        name = self.lineEdit.text()
        image = self.comboBox.currentText()
        gui = self.checkBox.isChecked()
        vnet = self.lineEdit_2.text()
        isolated = self.checkBox_3.isChecked()

        args = ""
        if gui:
            args += " -x"
        if vnet != "":
            args += " -c {}".format(vnet)
        if isolated:
            args += " -i"
        
        command = "vm-create {} -d {} {}".format(args,image,name)
        print(command)
        p = subprocess.Popen(command, stdout=subprocess.PIPE, shell=True)
        (output, err) = p.communicate()
        p_status = p.wait()
        print(output)
        self.lineEdit.setText("")
        self.checkBox.setChecked(False)
        self.lineEdit_2.setText("")
        self.checkBox_3.setChecked(False)
        MainWindow.close()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
