# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './UI2/vnCreationPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys, subprocess


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mainlabel = QtWidgets.QLabel(self.centralwidget)
        self.mainlabel.setGeometry(QtCore.QRect(10, 10, 321, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        self.mainlabel.setFont(font)
        self.mainlabel.setObjectName("mainlabel")
        self.nameLabel = QtWidgets.QLabel(self.centralwidget)
        self.nameLabel.setGeometry(QtCore.QRect(10, 70, 58, 18))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.nameLabel.setFont(font)
        self.nameLabel.setObjectName("nameLabel")
        self.nameLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.nameLineEdit.setGeometry(QtCore.QRect(70, 60, 211, 41))
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.cancelButton = QtWidgets.QPushButton(self.centralwidget)
        self.cancelButton.setGeometry(QtCore.QRect(450, 440, 88, 34))
        self.cancelButton.setObjectName("cancelButton")
        self.createButton = QtWidgets.QPushButton(self.centralwidget)
        self.createButton.setGeometry(QtCore.QRect(540, 440, 88, 34))
        self.createButton.setObjectName("createButton")
        self.dnsLabel = QtWidgets.QLabel(self.centralwidget)
        self.dnsLabel.setGeometry(QtCore.QRect(10, 120, 261, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dnsLabel.setFont(font)
        self.dnsLabel.setObjectName("dnsLabel")
        self.dnsCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.dnsCheckBox.setGeometry(QtCore.QRect(270, 120, 101, 22))
        self.dnsCheckBox.setObjectName("dnsCheckBox")
        self.internalCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.internalCheckBox.setGeometry(QtCore.QRect(520, 160, 101, 22))
        self.internalCheckBox.setObjectName("internalCheckBox")
        self.internalLabel = QtWidgets.QLabel(self.centralwidget)
        self.internalLabel.setGeometry(QtCore.QRect(10, 160, 501, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.internalLabel.setFont(font)
        self.internalLabel.setObjectName("internalLabel")
        self.subnetLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.subnetLineEdit.setGeometry(QtCore.QRect(10, 230, 271, 41))
        self.subnetLineEdit.setText("")
        self.subnetLineEdit.setFrame(True)
        self.subnetLineEdit.setDragEnabled(False)
        self.subnetLineEdit.setClearButtonEnabled(False)
        self.subnetLineEdit.setObjectName("subnetLineEdit")
        self.subnetLabel = QtWidgets.QLabel(self.centralwidget)
        self.subnetLabel.setGeometry(QtCore.QRect(10, 200, 511, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.subnetLabel.setFont(font)
        self.subnetLabel.setObjectName("subnetLabel")
        self.subnet2Label = QtWidgets.QLabel(self.centralwidget)
        self.subnet2Label.setGeometry(QtCore.QRect(290, 240, 201, 18))
        self.subnet2Label.setObjectName("subnet2Label")
        self.gatewayLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.gatewayLineEdit.setGeometry(QtCore.QRect(10, 320, 271, 41))
        self.gatewayLineEdit.setText("")
        self.gatewayLineEdit.setFrame(True)
        self.gatewayLineEdit.setDragEnabled(False)
        self.gatewayLineEdit.setClearButtonEnabled(False)
        self.gatewayLineEdit.setObjectName("gatewayLineEdit")
        self.gatewayLabel = QtWidgets.QLabel(self.centralwidget)
        self.gatewayLabel.setGeometry(QtCore.QRect(10, 290, 511, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.gatewayLabel.setFont(font)
        self.gatewayLabel.setObjectName("gatewayLabel")
        self.gateway2Label = QtWidgets.QLabel(self.centralwidget)
        self.gateway2Label.setGeometry(QtCore.QRect(290, 330, 201, 18))
        self.gateway2Label.setObjectName("gateway2Label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.mainlabel.setText(_translate("MainWindow", "Virtual Network - Creation"))
        self.nameLabel.setText(_translate("MainWindow", "Name : "))
        self.cancelButton.setText(_translate("MainWindow", "Cancel"))
        self.createButton.setText(_translate("MainWindow", "Create"))
        self.dnsLabel.setText(_translate("MainWindow", "Do you want to disable the DNS ?"))
        self.dnsCheckBox.setText(_translate("MainWindow", "Yes "))
        self.internalCheckBox.setText(_translate("MainWindow", "Yes "))
        self.internalLabel.setText(_translate("MainWindow", "Do you want to make this network \"internal\" (no external access) ?"))
        self.subnetLabel.setText(_translate("MainWindow", "Do you want a specific subnet for your network ? (e.g. 10.88.0.0/16)"))
        self.subnet2Label.setText(_translate("MainWindow", "Leave Empty if you don\'t want to"))
        self.gatewayLabel.setText(_translate("MainWindow", "Do you want a specific gateway ? (e.g. 10.88.0.1)"))
        self.gateway2Label.setText(_translate("MainWindow", "Leave Empty if you don\'t want to"))
        self.cancelButton.clicked.connect(sys.exit)
        self.createButton.clicked.connect(self.createVN)

           
    def createVN(self):
        name = self.nameLineEdit.text()
        disableDNS = self.dnsCheckBox.isChecked()
        internal = self.internalCheckBox.isChecked()
        subnet = self.subnetLineEdit.text()
        gateway = self.gatewayLineEdit.text()

        if name == "":
            dialog = QtWidgets.QMessageBox()
            dialog.setWindowTitle("theVirtualThings - Error")
            dialog.setIcon(QtWidgets.QMessageBox.Critical)
            dialog.setText("You must provide a name for the VN.")
            dialog.exec_()
            return False

        args = ""
        if disableDNS:
            args += " -d"
        if internal:
            args += " -i"
        if subnet != "":
            args += " -s {}".format(subnet)
        if gateway != "":
            args += " -g {}".format(gateway)

        
        command = "vn-create {} {}".format(args,name)
        p = subprocess.Popen(command, stdout=subprocess.PIPE, shell=True)
        (output, err) = p.communicate()
        p_status = p.wait()
        if p_status != 0:
            dialog = QtWidgets.QMessageBox()
            dialog.setWindowTitle("theVirtualThings - Error")
            dialog.setIcon(QtWidgets.QMessageBox.Critical)
            dialog.setText(f"An error occured while creating the VN.\n{err}")
            dialog.exec_()
            return False
        else:
            dialog = QtWidgets.QMessageBox()
            dialog.setWindowTitle("theVirtualThings - Success")
            dialog.setIcon(QtWidgets.QMessageBox.Information)
            dialog.setText("The VN has been created successfully :)")
            dialog.exec_()
            app.quit()



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
